//! Shared test-data resolution for the data-dependent integration tests.
//!
//! # Why this module exists
//!
//! Before 2026-08-16 each data-dependent test opened with:
//!
//! ```ignore
//! if !test_data_available() { eprintln!("Skipping ..."); return; }
//! ```
//!
//! and `test_data_available()` probed the two *relative* paths `data/` and
//! `../data/`. Those resolve correctly from a plain checkout of this repo
//! (`../data` is the pipeline data symlink) but **miss from a git worktree**
//! under `.worktrees/<name>/`, which sits two levels deeper. The measured
//! consequence in `.worktrees/backbone-v5` on 2026-08-16:
//!
//! ```text
//! running 21 tests
//! test result: ok. 21 passed; 0 failed; ... finished in 0.01s
//! ```
//!
//! against 639 s on a checkout that could see the data — i.e. **13 of 21
//! tests reported `ok` without executing a single assertion**, and the suite
//! was used as evidence that a decoder change was behaviour-preserving.
//!
//! A test that silently reports `ok` without running is worse than no test:
//! it is an *affirmative* signal of correctness generated by a code path
//! that checked nothing. This module makes that state impossible to reach by
//! accident.
//!
//! # Contract
//!
//! Resolution order for the pipeline `data/` root:
//!
//! 1. `$HFT_TEST_DATA_DIR`, if set — used **verbatim and exclusively**. An
//!    explicit override is never silently backed up by a relative guess; if
//!    it is wrong the tests fail and name it.
//! 2. otherwise the relative probes `data`, `../data`, ... up to 5 levels up,
//!    which covers a plain checkout (`../data`) and a worktree nested under
//!    `.worktrees/<name>/` (`../../../data`).
//!
//! A candidate root is accepted only when the *marker* the caller actually
//! needs exists beneath it, so a stray empty `data/` directory somewhere on
//! the ancestor chain cannot be selected.
//!
//! # Failure policy
//!
//! Missing data is a **hard failure** (panic). Set `ALLOW_MISSING_TEST_DATA=1`
//! to downgrade it to a loud skip — for example on a machine that has the
//! repo but not the ~100 GB data volume:
//!
//! ```bash
//! # normal: data-dependent tests must really run
//! cargo test --test integration_test
//!
//! # worktree / non-standard data location
//! HFT_TEST_DATA_DIR=/Users/you/code/HFT-pipeline-v2/data cargo test
//!
//! # explicit, acknowledged opt-out (coverage is REDUCED)
//! ALLOW_MISSING_TEST_DATA=1 cargo test
//! ```

#![allow(dead_code)] // each test binary uses a different subset of this module

use std::path::{Path, PathBuf};
use std::sync::Once;

/// Absolute (or relative) path to the pipeline `data/` root. Overrides all
/// relative probing when set.
pub const DATA_DIR_ENV: &str = "HFT_TEST_DATA_DIR";

/// Opt-out that downgrades missing test data from a panic to a loud skip.
pub const ALLOW_MISSING_ENV: &str = "ALLOW_MISSING_TEST_DATA";

/// How many parent levels to probe for a `data/` directory.
///
/// 3 is the minimum that reaches the pipeline root from
/// `MBO-LOB-reconstructor/.worktrees/<name>/`; 5 leaves headroom for a
/// deeper worktree layout without turning into an unbounded filesystem walk.
const MAX_PARENT_PROBE_DEPTH: usize = 5;

/// Candidate `data/` roots, in probe order.
///
/// `cargo test` runs each test binary with the *package* root as the working
/// directory, so these are relative to the crate (or worktree) root.
fn candidate_roots() -> Vec<PathBuf> {
    if let Some(dir) = std::env::var_os(DATA_DIR_ENV) {
        // Explicit override wins outright and is deliberately NOT combined
        // with the relative fallbacks: a typo in the variable must surface as
        // a failure naming the variable, not as a silent fallback to some
        // other tree's data.
        return vec![PathBuf::from(dir)];
    }

    let mut roots = Vec::with_capacity(MAX_PARENT_PROBE_DEPTH + 1);
    roots.push(PathBuf::from("data"));
    let mut up = PathBuf::from("..");
    for _ in 0..MAX_PARENT_PROBE_DEPTH {
        roots.push(up.join("data"));
        up = up.join("..");
    }
    roots
}

/// Resolve `marker` (a path relative to the pipeline `data/` root) against the
/// first candidate root that actually contains it.
///
/// Returns `None` when no candidate root contains `marker`. Callers that need
/// the data should use [`require_data_path`] instead, which enforces the
/// failure policy documented at the module level.
pub fn resolve_data_path(marker: &str) -> Option<PathBuf> {
    for root in candidate_roots() {
        let candidate = root.join(marker);
        if candidate.exists() {
            announce_root(&root);
            return Some(candidate);
        }
    }
    None
}

/// Print the resolved data root once per test binary, so a run's output
/// records *which* data it actually consumed.
fn announce_root(root: &Path) {
    static ANNOUNCE: Once = Once::new();
    ANNOUNCE.call_once(|| {
        let shown = root
            .canonicalize()
            .unwrap_or_else(|_| root.to_path_buf())
            .display()
            .to_string();
        eprintln!("ℹ️  test data root: {shown}");
    });
}

/// True when the operator has explicitly acknowledged running without data.
pub fn missing_data_allowed() -> bool {
    match std::env::var(ALLOW_MISSING_ENV) {
        Ok(v) => {
            let v = v.trim();
            !v.is_empty() && v != "0" && !v.eq_ignore_ascii_case("false")
        }
        Err(_) => false,
    }
}

/// Resolve `marker` under the pipeline `data/` root, or fail loudly.
///
/// Returns `Some(path)` when the data is present.
///
/// Returns `None` **only** when the data is absent *and* `ALLOW_MISSING_TEST_DATA`
/// is set — the caller is then expected to `return` early, and the skip has
/// been announced on stderr.
///
/// # Panics
///
/// When the data is absent and the opt-out is not set. This is deliberate:
/// see the module docs for the silent-`ok` failure this prevents.
pub fn require_data_path(marker: &str) -> Option<PathBuf> {
    if let Some(path) = resolve_data_path(marker) {
        return Some(path);
    }
    fail_or_skip(&missing_data_report(marker))
}

/// Enforce the missing-data policy for a caller that resolves its own inputs
/// (e.g. "the directory resolved but contains no matching file", which
/// [`require_data_path`] cannot detect because the directory itself exists).
///
/// Returns `None` when `ALLOW_MISSING_TEST_DATA` is set.
///
/// # Panics
///
/// Otherwise — see the module docs.
pub fn fail_or_skip(what: &str) -> Option<PathBuf> {
    let diagnosis = format!("{what}\n{}", fix_instructions());

    if missing_data_allowed() {
        eprintln!(
            "⚠️  {ALLOW_MISSING_ENV} is set — running WITHOUT data-dependent coverage.\n{diagnosis}"
        );
        return None;
    }

    panic!("{diagnosis}");
}

/// The two ways out of a missing-data failure, plus why it is a failure.
///
/// Shared so that every missing-data panic in the suite ends with the same
/// actionable tail regardless of which call site raised it.
fn fix_instructions() -> String {
    format!(
        "  fix one of:\n    \
         - point the tests at the data root: {DATA_DIR_ENV}=/abs/path/to/HFT-pipeline-v2/data\n    \
         - acknowledge reduced coverage:     {ALLOW_MISSING_ENV}=1\n  \
         this is a hard failure by design: a data-dependent test that returns\n  \
         early reports `ok` while asserting nothing, which has previously been\n  \
         mistaken for evidence that a change was behaviour-preserving."
    )
}

/// Human-readable diagnosis of a failed resolution: what was wanted and where
/// we looked. The shared [`fix_instructions`] tail is appended by
/// [`fail_or_skip`].
fn missing_data_report(marker: &str) -> String {
    let cwd = std::env::current_dir()
        .map(|p| p.display().to_string())
        .unwrap_or_else(|e| format!("<unavailable: {e}>"));

    let override_note = match std::env::var(DATA_DIR_ENV) {
        Ok(v) => format!("{DATA_DIR_ENV} is set to {v:?} and does not contain the marker"),
        Err(_) => format!("{DATA_DIR_ENV} is not set (relative probing was used)"),
    };

    let probed = candidate_roots()
        .iter()
        .map(|r| format!("    - {}", r.join(marker).display()))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "test data not found\n  \
         marker (relative to the pipeline `data/` root):\n    {marker}\n  \
         working directory:\n    {cwd}\n  \
         {override_note}\n  \
         probed:\n{probed}"
    )
}
